import { Program, Type, Model, getTypeName, navigateProgram } from "@typespec/compiler";
import { getGoType } from "./go-types.js";
import { join } from "path";

export interface EmitterOptions {
  packageName?: string;
  outputDir?: string;
}

export class GoEmitter {
  private program: Program | Record<string, Type>;
  private options: Required<EmitterOptions>;
  private imports: Set<string>;

  constructor(program: Program | Record<string, Type>, options: EmitterOptions = {}) {
    this.program = program;
    this.options = {
      packageName: options.packageName || "api",
      outputDir: options.outputDir || "generated",
    };
    this.imports = new Set<string>();
  }

  generateModelCode(model: Model): string {
    const modelName = getTypeName(model);
    let code = `// ${modelName} represents a generated model\n`;
    code += `type ${modelName} struct {\n`;

    // Generate struct fields
    for (const [propName, prop] of model.properties) {
      const goType = getGoType(this.program as Program, prop.type);
      if (goType.imports) {
        goType.imports.forEach((imp) => this.imports.add(imp));
      }

      const fieldType = goType.isPointer ? `*${goType.name}` : goType.name;
      code += `\t${propName} ${fieldType} \`json:"${propName}${prop.optional ? ",omitempty" : ""}"\`\n`;
    }

    code += "}\n\n";
    return code;
  }

  generateFileHeader(): string {
    let header = `// Code generated by @common-grants/typespec-go. DO NOT EDIT.\n\n`;
    header += `package ${this.options.packageName}\n\n`;

    if (this.imports.size > 0) {
      header += "import (\n";
      this.imports.forEach((imp) => {
        header += `\t"${imp}"\n`;
      });
      header += ")\n\n";
    }

    return header;
  }

  async emit(): Promise<Map<string, string>> {
    const files = new Map<string, string>();
    const models = new Set<Model>();

    // Collect all models from the program
    navigateProgram(this.program as Program, {
      model: (model) => {
        // Skip built-in models and those from other libraries
        if (!model.name.startsWith("TypeSpec.") && !model.name.includes("@typespec")) {
          models.add(model);
        }
      },
    });

    if (models.size > 0) {
      let modelsContent = "";
      
      // Generate code for each model
      for (const model of models) {
        modelsContent += this.generateModelCode(model);
      }

      // Create the complete file content with header
      const fullContent = this.generateFileHeader() + modelsContent;
      
      // Store the generated file
      const outputPath = join(this.options.outputDir, "models.go");
      files.set(outputPath, fullContent);
    }

    return files;
  }
} 